---
title: "R Notebook"
output: html_notebook
---

```{r}
# Tidy data lab 

# Task 1.
# Load in the country_data.csv file and take a look at it. What needs changed in this to make it tidy? Which columns need made into long format, and which need spread to rows?
# 
# 
# Task 2.
# Do the appropriate pivoting of your columns using R
# 
# 
# Task 3.
# Separate the country variable so you have the name in one column and the number in another.
# 
# 
# Task 4.
# Unite the code_letter and code_numb variables so that they are both in one column, with no spaces separating them.
```

```{r}
library(tidyverse)
country_data <- read_csv("4_tidy_data_mini_lab/data/country_data.csv")
```

```{r}
country_data_long <- country_data %>%
  pivot_longer(
    cols = starts_with("Y"),
    names_to = "year",
    values_to = "count",
    names_prefix = "Y"
  )

country_data_wide <- country_data_long %>%
  pivot_wider(
    names_from = "type",
    values_from = "count"
  )

```

```{r}
country_data_non_coded <- country_data_wide %>%
  separate(country,
           c("code_numb", "country"),
             sep = "\\."
  )

```

```{r}
country_data_united <- country_data_non_coded %>%
  unite(code, c("code_numb", "code_letter"),
        sep = ""
  )

```

