---
title: "R Notebook"
output: html_notebook
---

```{r}
# What is tidy data?

# Tidy data has structure
# 1. Every variable has its own column
# 2. Each observation has its own row
# 3. Each value must have its own cell (e.g. not Joe Bloggs, 28)

# Tidy data has relationships (e.g. relationship between name and bank account number)

```

```{r}
# Some terminology

# Long format - every row represents an observation belonging to a particular category
# Wide format - observations are spread across multiple columns

```

```{r}
# tidyr package

# pivot_longer() - gathers columns into rows
# pivot_wider() - spreads rows into columns
# seperate() - seperates one column into two
# unite() - unites several into one

```

```{r}
# create subject info tibble
subject_hr <- tibble( name = c("SUBJ01","SUBJ02","SUBJ03"), 
  hr_am = c(68,72,68), 
  hr_pm = c(58,89,52))
subject_hr


```

```{r}
subject_hr %>%
  pivot_longer(cols = c("hr_am", "hr_pm"),
               names_to = "measurement_time",
               names_prefix = "hr_",
               values_to = "heartrate")
```


```{r}
income <- tibble(religion = c("Agnostic","Atheist","Buddhist", "Catholic"), 
  X10k = c(12,25,3,75), 
  X10k_to_20k = c(34,14,6,60),
  X20k_to_30k = c(45,22,10,110))

income

```

```{r}
tidy_income <- income %>%
  pivot_longer(
    -religion,
    names_to = "income_band",
    values_to = "count"
  )
```

```{r}
messy_orders <- tibble( name = c("Joe Bloggs","Jane Smith","Penny Jones"), 
  order_info = c("XY7282/29-06-19","LO0182/15-03-19","AS6812/04-06-19"), 
  order_amount = c(58.00,125.00,75.25))

messy_orders

tidy_orders <- messy_orders %>%
  separate(order_info, 
    c("order_number", "date"),
    sep = "/"
  )

```

```{r}
hospital_visits <- read_csv("3_tidy_data/data/hospitals93to98.csv")
```

```{r}
hospital_visits_long <- hospital_visits %>%
    pivot_longer(cols = starts_with("FY"),
                 names_to = "year",
                 values_to = "visit_numbers",
                 names_prefix = "FY"
                 )
```

```{r}
hospital_visits_wide <- hospital_visits_long %>%
  pivot_wider(names_from = "Field",
              values_from = "visit_numbers"
  )

```

```{r}
hospital_visits_coded <- hospital_visits_wide %>%
  separate(IcdChapter,
           c("code", "description"), sep = "\\.")

```


```{r}
hospital_visits_unite <- hospital_visits_coded %>%
  unite(disease,
        c("code", "description"),
        sep = ":"
  )

```

